author: Jaimss
version: 1.0.3
name: DragVouchers
description: A vouchers plugin that uses the inventory click event.
main: dev.jaims.dragvouchers.DragVouchers
api-version: 1.16

softdepend:
  - TokenEnchant